### PR TITLE
Boost-CI/atan2/tests

### PR DESCRIPTION
**Pull request by kedarbhat**
* Contains changes related to Boost-CI #2  
  * cppcheck works locally, but I wasn't able to get it to work on Travis
  * I wasn't able to get Coverity Scan to work either locally or on Travis. I used [Boost.Units](https://github.com/boostorg/units) as the model for this, but I'm missing something on having a build accepted.
* Contains changes already contained in PR #23 
* Updated tests with less wonky function domains

### CODE REVIEW

**Comment by kedarbhat** [comment]
The coverage ratios change significantly with the underlying changes:
1. Only files in `include/boost/math/differentiation` are measured
2. Lines are categorized as "hit", "missed", and "partial". Some former "hits" are now being classified as "partial".

**Comment by kedarbhat** [comment]
Are you able to merge this PR while ignoring autodiff.hpp and autodiff_cpp11.hpp? The changes in those files are are related only what is resolved in PR #24.

**Comment by pulver** [comment]
> Are you able to merge this PR while ignoring autodiff.hpp and autodiff_cpp11.hpp? The changes in those files are are related only what is resolved in PR #24.

I'm not sure off-hand. I will look into that in the next day or so.

I looked over the rest of the changes. I don't see any objections, but I'd be interested in asking how you feel about the overall changes? Is it a sensible way to do things that is an improvement in how we/you have been doing the tests?

**Comment by kedarbhat** [comment]
> > Are you able to merge this PR while ignoring autodiff.hpp and autodiff_cpp11.hpp? The changes in those files are are related only what is resolved in PR #24.
> 
> I'm not sure off-hand. I will look into that in the next day or so.
> 
> I looked over the rest of the changes. I don't see any objections, but I'd be interested in asking how you feel about the overall changes? Is it a sensible way to do things that is an improvement in how we/you have been doing the tests?

This set of tests is mostly identical to what’s in your develop branch; the difference is that the domains are trimmed to something more realistic. Since the tests are meant to verify behavior is identical between AD types and root types for a given function, I think using pseudo-random data has been helpful to uncover some issues (ie 
[Boost Multiprecision #120](https://github.com/boostorg/multiprecision/issues/120).

Since there are clearly still differences between results (hence wider tolerances), I think that should be the next step after pow is re-implemented (that being the only function I see as remaining on your TODO list), differences should be solved.

**Comment by kedarbhat** [comment]
I updated the PR to reflect the changes in your [dev-atan2](https://github.com/pulver/autodiff/tree/dev-atan2) branch; specifically, autodiff*.hpp should be identical or nearly identical (whitespace not withstandanding).

I also removed the commented out hackery for cppcheck/CoverityScan from .travis.yml since I'm not able to get either to work on Travis anyway; I reverted to what @jeking3 has in [Boost.Boost-CI](www.github.com/boostorg/boost-ci).

Regarding testing, do you have any thoughts or suggestions on improving that process?

**Comment by pulver** [comment]
Thanks for the update. That will make merging easier.

> Regarding testing, do you have any thoughts or suggestions on improving that process?

Not with respect to this PR. If I do in the future, I'll make it a separate issue.

**Comment by shaneasd** [comment]
Regarding the use of random unit test cases they have some pretty nice advantages but some pretty big drawbacks.

Advantages:
- every time you run the test you'll test different values so over time your test coverage is very high
- you don't have to put a lot of thought into picking edge case test values

Disadvantages:
- every time you run the test you'll test different values so if there is a bug for a small subset of values then your test will randomly fail. Depending on who this happens to it might cause a lot of confusion. An example of this is tgamma which gives incorrect derivatives for all integer inputs if, as in the existing unit test, we pick values in the range 0-1000 and given that float has about 7 decimal digits of precision then for every integer in that range there'd be approximately a 10000x chance of randomly selecting a non-integer. For 25 samples thats a 99.7% chance of such a test missing the integers and passing erroneously. If you hard coded the test cases and overlooked the integer special case then you'd have a 100% chance of passing erroneously but at least the passing state would be the same for all users at all times.

I think random numbers are a great way of generating interesting test cases particularly in early development but I think before pushing your library out to a wider audience (i.e. maybe not yet) it makes sense to cement those test cases in by hard coding them and make your unit tests deterministic (even if you still use a pseudo-random generator seeded with a constant.

**Comment by kedarbhat** [comment]
> Regarding the use of random unit test cases they have some pretty nice advantages but some pretty big drawbacks.
> 
> Advantages:
> 
> * every time you run the test you'll test different values so over time your test coverage is very high
> * you don't have to put a lot of thought into picking edge case test values
> 
> Disadvantages:
> 
> * every time you run the test you'll test different values so if there is a bug for a small subset of values then your test will randomly fail. Depending on who this happens to it might cause a lot of confusion. An example of this is tgamma which gives incorrect derivatives for all integer inputs if, as in the existing unit test, we pick values in the range 0-1000 and given that float has about 7 decimal digits of precision then for every integer in that range there'd be approximately a 10000x chance of randomly selecting a non-integer. For 25 samples thats a 99.7% chance of such a test missing the integers and passing erroneously. If you hard coded the test cases and overlooked the integer special case then you'd have a 100% chance of passing erroneously but at least the passing state would be the same for all users at all times.
> 
> I think random numbers are a great way of generating interesting test cases particularly in early development but I think before pushing your library out to a wider audience (i.e. maybe not yet) it makes sense to cement those test cases in by hard coding them and make your unit tests deterministic (even if you still use a pseudo-random generator seeded with a constant.

Good points. I do agree having known input/output pairs (tuples?) is would be valuable to use in addition to random inputs (the known inputs/outputs being the foundation of the testing).

25 samples was only set (in `test_autodiff.hpp`) for the sake of increasing the ability to iterate. It can obviously be increased or decreased, and I do agree, before publishing the library into the wild, there should be more iterations per test (since presumably, at that point, we wouldn't be optimizing for iteration speed anymore).

Regarding problematic inputs (integral or otherwise), I should add back the try/catch phrases and add known problematic inputs per function to test that the functions do indeed throw exceptions or have floating point errors, whichever is expected; the previous try/catch code was actually meant to make sure that if the call with `autodiff_fvar` caused an exception, the call with `root_type` would do the same; a few issues were found this way.

**Comment by pulver** [comment]
Hi @kedarbhat,

Is this an appropriate squash commit message for this PR? I know a lot is included in the first 2 bullet points. It's always easier to detail what one's self has done rather than another, so if there is some major work that should be specified in greater detail, please let me know so it get properly recorded. (The unsquashed list of commits is too long and detailed.)

* integrate Boost-CI (@kedarbhat)
* upgrade all tests (@kedarbhat)
* Generalize apply_coefficients() helper methods to multiple variables.
* Apply new apply_coefficients() to fvar::atan2() overloads.
* Add fvar::negate().
* Facilitate NRVO and related optimizations in numerous places. (Thanks to @shaneasd for discussion.)
* Rename apply_* methods with better uniformity.
* Rewrite fourth_power.cpp with NRVO and comments.
* Upgrade boost in ci tests to 1.70.0 beta1.

**Comment by kedarbhat** [comment]
Yea, I think that's appropriate. It's not hard to suss out the detail of any particular point if one so wishes anyway.

I'm working on the way codecov.io is measuring coverage; it does point out a few small things that might be worth looking at, but mostly, it's picking up branches within standard library code (as far as I can tell); I don't see how a std::for_each could possibly have a partial hit (for instance).

**Pull request merged**
